[tool.poetry]
name = "kaitai"
version = "0.1.0"
description = ""
authors = ["Vector35"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
kaitaistruct = "^0.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
